name: Bug Report
description: Report a problem with codepass
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      placeholder: Describe the bug
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      value: |
        1. Ran `/codepass:pr-review ...`
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What should have happened?
    validations:
      required: true
  - type: input
    id: claude-version
    attributes:
      label: Claude Code version
      placeholder: "Output of: claude --version"
    validations:
      required: true
  - type: input
    id: gh-version
    attributes:
      label: gh CLI version
      placeholder: "Output of: gh --version"
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options:
        - macOS
        - Linux
        - Windows (WSL)
    validations:
      required: true
